version: "3.8"

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - node
    networks:
      - app-network

  node:
    image: node:20-alpine
    working_dir: /app
    container_name: privacyvet
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
